/**
 * nib storybook init — one-time Storybook integration setup.
 *
 * 1. Validates preconditions (brand.config.json + variables.css must exist)
 * 2. Detects framework, package manager, and Storybook version from package.json
 * 3. Creates/patches .storybook/main.ts and .storybook/preview.ts
 * 4. Creates .storybook/nib-theme-decorator.ts (always written, idempotent)
 * 5. Creates src/stories/DesignTokens.mdx (skipped if exists)
 * 6. Prints install command + file summary
 */

import { existsSync } from "node:fs";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { isAbsolute, join, relative } from "node:path";
import pc from "picocolors";
import { patchAddonsArray, patchDecorators, patchPreviewImports, patchStaticDirs } from "./patch.js";

export interface StorybookInitResult {
  framework: string;
  sbVersion: number;
  packageManager: string;
  filesCreated: string[];
  filesPatched: string[];
  warnings: string[];
  installCommand: string;
}

// ---------------------------------------------------------------------------
// Detection helpers
// ---------------------------------------------------------------------------

interface PackageJson {
  dependencies?: Record<string, string>;
  devDependencies?: Record<string, string>;
}

function readAllDeps(pkg: PackageJson): Record<string, string> {
  return { ...pkg.dependencies, ...pkg.devDependencies };
}

function detectFramework(deps: Record<string, string>): string {
  if ("react" in deps) return "react";
  if ("vue" in deps) return "vue3";
  if ("svelte" in deps) return "svelte";
  if ("lit" in deps) return "web-components";
  return "unknown";
}

function detectSbVersion(deps: Record<string, string>): number {
  const sbPkg = deps["storybook"] ?? deps["@storybook/core"] ?? "";
  const match = sbPkg.match(/(\d+)\./);
  if (match?.[1]) return parseInt(match[1], 10);
  // Check for any @storybook/* package
  for (const [key, ver] of Object.entries(deps)) {
    if (key.startsWith("@storybook/")) {
      const m = ver.match(/(\d+)\./);
      if (m?.[1]) return parseInt(m[1], 10);
    }
  }
  return 9; // default assumption
}

function detectPackageManager(cwd: string): string {
  if (existsSync(join(cwd, "pnpm-lock.yaml"))) return "pnpm";
  if (existsSync(join(cwd, "yarn.lock"))) return "yarn";
  return "npm";
}

function sbDesignTokenVersion(sbMajor: number): string {
  if (sbMajor >= 10) return "storybook-design-token@^5";
  if (sbMajor >= 9) return "storybook-design-token@^4";
  return "storybook-design-token@^2.9"; // SB 8.x
}

function installCmd(pm: string, packages: string[]): string {
  const pkgStr = packages.join(" ");
  if (pm === "pnpm") return `pnpm add -D ${pkgStr}`;
  if (pm === "yarn") return `yarn add -D ${pkgStr}`;
  return `npm install -D ${pkgStr}`;
}

// ---------------------------------------------------------------------------
// File templates
// ---------------------------------------------------------------------------

function mainTemplate(framework: string, tokenCssDir: string): string {
  const sbFramework = framework === "unknown"
    ? "/* PLACEHOLDER: replace with your @storybook/<framework>-vite package */"
    : `"@storybook/${framework}-vite"`;

  return `import type { StorybookConfig } from "@storybook/${framework === "unknown" ? "react" : framework}-vite";

// Configured by nib storybook init
const config: StorybookConfig = {
  stories: ["../src/**/*.mdx", "../src/**/*.stories.@(js|jsx|mjs|ts|tsx)"],
  addons: [
    "@storybook/addon-essentials",
    "@storybook/addon-themes",
    {
      name: "storybook-design-token",
      options: {
        // Points to the static dir so the addon can scan CSS annotations
        cssFiles: ["variables.css"],
      },
    },
  ],
  framework: {
    name: ${sbFramework},
    options: {},
  },
  // Serve nib build output as static — storybook-design-token reads from here
  staticDirs: ["../${tokenCssDir}"],
  docs: {},
};

export default config;
`;
}

function themeDecoratorTemplate(brandName: string): string {
  return `// Generated by nib storybook init — Brand: ${brandName}
// Applies nib's [data-theme] attribute for light/dark switching.
// nib semantic tokens use [data-theme="dark"] selector in variables.css.

import { withThemeByDataAttribute } from "@storybook/addon-themes";

export const nibThemeDecorator = withThemeByDataAttribute({
  themes: {
    Light: "light",
    Dark: "dark",
  },
  defaultTheme: "Light",
  attributeName: "data-theme",
});
`;
}

function previewTemplate(
  brandName: string,
  cssRelativePath: string,
  defaultTab: string,
  showSearch: boolean,
): string {
  return `// Generated by nib storybook init — Brand: ${brandName}
// Note: Multi-brand Storybook support (swapping variables.css at runtime) is
// not supported in this release. One brand per Storybook instance.

import type { Preview } from "@storybook/react-vite";
import { nibThemeDecorator } from "./nib-theme-decorator";

// nib brand tokens — CSS custom properties
import "${cssRelativePath}";

const preview: Preview = {
  tags: ["autodocs"],

  parameters: {
    layout: "centered",
    // storybook-design-token panel config
    designToken: {
      defaultTab: "${defaultTab}",
      showSearch: ${showSearch},
    },
    backgrounds: { disable: true }, // nib uses data-theme instead
  },

  decorators: [nibThemeDecorator],
};

export default preview;
`;
}

function designTokensMdxTemplate(brandName: string): string {
  return `import { Meta } from "@storybook/blocks";

<Meta title="Design System / ${brandName} Brand Tokens" />

# ${brandName} Brand Tokens

This design system is powered by **nib** — the design control plane for the ${brandName} brand.

## About

Design tokens are defined in \`docs/design/system/build/css/variables.css\` and generated
by \`nib brand build\`. They are available as CSS custom properties (\`var(--token-name)\`)
in all components.

Use the **Design Token** panel (bottom toolbar) to browse all token categories.

Use the **theme toggle** (top toolbar) to switch between Light and Dark modes.
Theming is implemented via \`[data-theme="dark"]\` CSS attribute — matching nib's output.

## Token Usage

\`\`\`css
/* Always use semantic tokens, not primitives */
color: var(--color-text-primary);
background: var(--color-background-primary);
border: 1px solid var(--color-border-primary);

/* Interactive elements */
background: var(--color-interactive-default);
color: var(--color-text-inverse);
\`\`\`

> Run \`nib brand build\` to regenerate tokens after changing brand guidelines.
> Run \`nib component story <Name>\` to scaffold a story for any component contract.
`;
}

// ---------------------------------------------------------------------------
// Main implementation
// ---------------------------------------------------------------------------

export async function storybookInit(cwd: string = process.cwd()): Promise<StorybookInitResult> {
  const filesCreated: string[] = [];
  const filesPatched: string[] = [];
  const warnings: string[] = [];

  // --- Precondition checks ---
  const configPath = join(cwd, ".nib", "brand.config.json");
  if (!existsSync(configPath)) {
    throw new Error(
      `No brand.config.json found at ${configPath}.\nRun ${pc.cyan("nib brand init")} first.`,
    );
  }

  const config = JSON.parse(await readFile(configPath, "utf8")) as {
    brand?: { name?: string };
    platforms?: { css?: string };
    storybook?: { defaultTab?: string; showSearch?: boolean };
  };

  const brandName = config.brand?.name ?? "Brand";
  const rawCssPath = config.platforms?.css ?? "docs/design/system/build/css/variables.css";
  // brand.config.json stores absolute paths — resolve to relative for template output
  const cssAbsPath = isAbsolute(rawCssPath) ? rawCssPath : join(cwd, rawCssPath);
  const cssOutputPath = isAbsolute(rawCssPath) ? relative(cwd, rawCssPath) : rawCssPath;
  const defaultTab = config.storybook?.defaultTab ?? "Semantic Colors";
  const showSearch = config.storybook?.showSearch ?? true;

  if (!existsSync(cssAbsPath)) {
    throw new Error(
      `No variables.css found at ${cssAbsPath}.\nRun ${pc.cyan("nib brand build")} first.`,
    );
  }

  // --- Detection ---
  let pkg: PackageJson = {};
  const pkgPath = join(cwd, "package.json");
  if (existsSync(pkgPath)) {
    pkg = JSON.parse(await readFile(pkgPath, "utf8")) as PackageJson;
  }
  const deps = readAllDeps(pkg);
  const framework = detectFramework(deps);
  const sbVersion = detectSbVersion(deps);
  const pm = detectPackageManager(cwd);

  if (framework === "unknown") {
    warnings.push(
      `Could not detect framework from package.json. Generated main.ts contains a PLACEHOLDER.\n` +
      `Add --framework react|vue|svelte|lit flag or edit the generated file manually.`,
    );
  }

  // --- .storybook dir ---
  const sbDir = join(cwd, ".storybook");
  await mkdir(sbDir, { recursive: true });

  // CSS dir to serve as staticDir (parent dir of variables.css, relative to project root)
  const cssDir = cssOutputPath.split("/").slice(0, -1).join("/"); // strip filename

  // --- .storybook/main.ts ---
  const mainTsPath = join(sbDir, "main.ts");
  const mainJsPath = join(sbDir, "main.js");
  if (!existsSync(mainTsPath) && !existsSync(mainJsPath)) {
    await writeFile(mainTsPath, mainTemplate(framework, cssDir));
    filesCreated.push(".storybook/main.ts");
  } else {
    const existingPath = existsSync(mainTsPath) ? mainTsPath : mainJsPath;
    const existingLabel = existsSync(mainTsPath) ? ".storybook/main.ts" : ".storybook/main.js";
    let src = await readFile(existingPath, "utf8");
    let changed = false;

    const addonResult = patchAddonsArray(src, ["@storybook/addon-themes", "storybook-design-token"]);
    if (addonResult.warning) warnings.push(addonResult.warning);
    if (addonResult.changed) { src = addonResult.patched; changed = true; }

    const staticResult = patchStaticDirs(src, cssDir);
    if (staticResult.warning) warnings.push(staticResult.warning);
    if (staticResult.changed) { src = staticResult.patched; changed = true; }

    if (changed) {
      await writeFile(existingPath, src);
      filesPatched.push(existingLabel);
    }
  }

  // --- .storybook/nib-theme-decorator.ts (always write) ---
  await writeFile(join(sbDir, "nib-theme-decorator.ts"), themeDecoratorTemplate(brandName));
  filesCreated.push(".storybook/nib-theme-decorator.ts");

  // --- .storybook/preview.ts ---
  const previewTsPath = join(sbDir, "preview.ts");
  const previewJsPath = join(sbDir, "preview.js");
  // Path to CSS relative from .storybook/ — go up one level
  const cssRelativeFromSb = `../${cssOutputPath}`;

  if (!existsSync(previewTsPath) && !existsSync(previewJsPath)) {
    await writeFile(previewTsPath, previewTemplate(brandName, cssRelativeFromSb, defaultTab, showSearch));
    filesCreated.push(".storybook/preview.ts");
  } else {
    const existingPath = existsSync(previewTsPath) ? previewTsPath : previewJsPath;
    const existingLabel = existsSync(previewTsPath) ? ".storybook/preview.ts" : ".storybook/preview.js";
    let src = await readFile(existingPath, "utf8");
    let changed = false;

    const cssResult = patchPreviewImports(src, cssRelativeFromSb);
    if (cssResult.changed) { src = cssResult.patched; changed = true; }

    const decoratorResult = patchDecorators(
      src,
      `import { nibThemeDecorator } from "./nib-theme-decorator"`,
      "nibThemeDecorator",
    );
    if (decoratorResult.warning) warnings.push(decoratorResult.warning);
    if (decoratorResult.changed) { src = decoratorResult.patched; changed = true; }

    if (changed) {
      await writeFile(existingPath, src);
      filesPatched.push(existingLabel);
    }
  }

  // --- src/stories/DesignTokens.mdx ---
  const storiesDir = join(cwd, "src", "stories");
  const mdxPath = join(storiesDir, "DesignTokens.mdx");
  if (!existsSync(mdxPath)) {
    await mkdir(storiesDir, { recursive: true });
    await writeFile(mdxPath, designTokensMdxTemplate(brandName));
    filesCreated.push("src/stories/DesignTokens.mdx");
  }

  // --- Install command ---
  const designTokenPkg = sbDesignTokenVersion(sbVersion);
  const installCommand = installCmd(pm, ["@storybook/addon-themes", designTokenPkg]);

  return { framework, sbVersion, packageManager: pm, filesCreated, filesPatched, warnings, installCommand };
}
