/**
 * nib component story — generate a .stories.ts scaffold from a component contract.
 *
 * Pure function: accepts a parsed ComponentContract, returns a file string.
 * Does not perform any file I/O.
 */

import type { ComponentContract } from "../types/brand.js";

export interface StoryGenOptions {
  /** Framework import path (default: react) */
  framework?: "react" | "vue3" | "svelte" | "web-components" | "unknown";
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/** PascalCase a string: "primary" → "Primary", "my-thing" → "MyThing" */
function pascal(s: string): string {
  return s
    .split(/[-_\s]+/)
    .map(w => w.charAt(0).toUpperCase() + w.slice(1))
    .join("");
}

/** Expand size key to English label */
function sizeLabel(key: string): string {
  const map: Record<string, string> = {
    xs: "XSmall",
    sm: "Small",
    md: "Medium",
    lg: "Large",
    xl: "XLarge",
    "2xl": "XXLarge",
  };
  return map[key] ?? pascal(key);
}

/** Convert a token path like "color.interactive.default" to a CSS var name */
function tokenToCssVar(tokenPath: string): string {
  return `var(--${tokenPath.replace(/\./g, "-")})`;
}

/** Build the framework import line for Meta/StoryObj */
function frameworkImport(fw: string): string {
  if (fw === "unknown") {
    return [
      `// PLACEHOLDER: replace with your framework import`,
      `// React:  import type { Meta, StoryObj } from "@storybook/react-vite";`,
      `// Vue:    import type { Meta, StoryObj } from "@storybook/vue3-vite";`,
      `// Svelte: import type { Meta, StoryObj } from "@storybook/svelte-vite";`,
      `import type { Meta, StoryObj } from "@storybook/react-vite";`,
    ].join("\n");
  }
  const sbPkg = fw === "react" ? "@storybook/react-vite" : `@storybook/${fw}-vite`;
  return `import type { Meta, StoryObj } from "${sbPkg}";`;
}

/** Build a11y description string from contract */
function buildA11yDescription(contract: ComponentContract): string {
  const parts: string[] = [];
  const a11y = contract.a11y as unknown as Record<string, unknown> | undefined;
  if (!a11y) return contract.description ?? "";

  if (contract.description) parts.push(contract.description);
  if (typeof a11y["role"] === "string") parts.push(`WCAG role: ${a11y["role"]}.`);

  const keyboard = a11y["keyboard"] as Record<string, string> | undefined;
  if (keyboard) {
    const keys = Object.entries(keyboard)
      .map(([k, v]) => `${k} — ${v}`)
      .join(". ");
    if (keys) parts.push(`Keyboard: ${keys}.`);
  }

  const ariaAttributes = a11y["ariaAttributes"] as string[] | undefined;
  if (ariaAttributes?.length) {
    parts.push(`ARIA attributes: ${ariaAttributes.join(", ")}.`);
  }

  return parts.join(" ");
}

/** Extract token presetColors from tokens.root.default */
function buildPresetColors(contract: ComponentContract): string[] {
  const tokens = contract.tokens as Record<string, unknown> | undefined;
  const rootDefault = (tokens?.["root"] as Record<string, unknown> | undefined)?.["default"] as
    | Record<string, string>
    | undefined;
  if (!rootDefault) return [];
  return Object.values(rootDefault)
    .filter(v => typeof v === "string" && v.startsWith("color."))
    .map(v => tokenToCssVar(v));
}

// ---------------------------------------------------------------------------
// Main export
// ---------------------------------------------------------------------------

export function generateStory(contract: ComponentContract, opts: StoryGenOptions = {}): string {
  const fw = opts.framework ?? "react";
  const name = contract.name;
  const variants = contract.variants as Record<string, string> | undefined;
  const sizes = contract.sizes as Record<string, unknown> | undefined;
  const states = contract.states as Record<string, { description?: string; ariaDisabled?: boolean; focusRing?: boolean }> | undefined;
  const anatomy = contract.anatomy as Record<string, string> | undefined;

  const variantKeys = variants ? Object.keys(variants) : [];
  const sizeKeys = sizes ? Object.keys(sizes) : [];
  const stateKeys = states ? Object.keys(states).filter(s => s !== "default") : [];
  const presetColors = buildPresetColors(contract);

  const lines: string[] = [];

  // Header
  lines.push(
    `/**`,
    ` * ${name} stories — generated by nib from .nib/components/${name}.contract.json`,
    ` * Run \`nib component story ${name} --overwrite\` to regenerate.`,
    ` *`,
    ` * NEXT STEPS:`,
    ` * 1. Replace the PLACEHOLDER import below with your real component import.`,
    ` * 2. Fill in the render function in AllVariants.`,
    ` * 3. Remove this comment block.`,
    ` */`,
    ``,
  );

  // Framework import
  lines.push(frameworkImport(fw), ``);

  // Component anatomy JSDoc + placeholder interface
  if (anatomy) {
    lines.push(`/**`);
    lines.push(` * Component anatomy:`);
    for (const [part, desc] of Object.entries(anatomy)) {
      lines.push(` * - ${part}: ${desc}`);
    }
    lines.push(` */`);
  }

  // Placeholder component import
  lines.push(
    `// PLACEHOLDER: Replace with your real component import.`,
    `// Example: import { ${name} } from "../components/${name}";`,
    `// eslint-disable-next-line @typescript-eslint/no-explicit-any`,
    `const ${name} = (_props: any): null => null;`,
    ``,
  );

  // Meta
  const a11yDesc = buildA11yDescription(contract);
  lines.push(`const meta = {`);
  lines.push(`  title: "Components/${name}",`);
  lines.push(`  component: ${name},`);
  lines.push(`  tags: ["autodocs"],`);
  lines.push(`  parameters: {`);
  lines.push(`    layout: "centered",`);
  lines.push(`    docs: {`);
  lines.push(`      description: {`);
  lines.push(`        component: "${a11yDesc.replace(/"/g, '\\"')}",`);
  lines.push(`      },`);
  lines.push(`    },`);
  lines.push(`  },`);

  // argTypes
  lines.push(`  argTypes: {`);

  if (variantKeys.length > 0) {
    const variantDesc = variantKeys
      .map(k => `${k}: ${variants![k]}`)
      .join("; ");
    lines.push(`    variant: {`);
    lines.push(`      control: "select",`);
    lines.push(`      options: [${variantKeys.map(k => `"${k}"`).join(", ")}],`);
    lines.push(`      description: "${variantDesc.replace(/"/g, '\\"')}",`);
    lines.push(`      table: { defaultValue: { summary: "${variantKeys[0]}" } },`);
    lines.push(`    },`);
  }

  if (sizeKeys.length > 0) {
    lines.push(`    size: {`);
    lines.push(`      control: "select",`);
    lines.push(`      options: [${sizeKeys.map(k => `"${k}"`).join(", ")}],`);
    lines.push(`      description: "Size variant",`);
    lines.push(`      table: { defaultValue: { summary: "${sizeKeys[Math.floor(sizeKeys.length / 2)]}" } },`);
    lines.push(`    },`);
  }

  if (stateKeys.some(s => s === "disabled")) {
    lines.push(`    disabled: { control: "boolean", description: "Disabled state" },`);
  }
  if (stateKeys.some(s => s === "loading")) {
    lines.push(`    loading: { control: "boolean", description: "Loading state" },`);
  }

  if (presetColors.length > 0) {
    lines.push(`    // Token preset colors from contract tokens.root.default:`);
    lines.push(`    // ${presetColors.join(", ")}`);
  }

  lines.push(`  },`);

  // Default args
  lines.push(`  args: {`);
  if (variantKeys[0]) lines.push(`    variant: "${variantKeys[0]}",`);
  if (sizeKeys.length > 0) lines.push(`    size: "${sizeKeys[Math.floor(sizeKeys.length / 2)]}",`);
  lines.push(`  },`);

  lines.push(`} satisfies Meta<typeof ${name}>;`, ``);
  lines.push(`export default meta;`);
  lines.push(`type Story = StoryObj<typeof meta>;`, ``);

  // Variant stories
  if (variantKeys.length > 0) {
    lines.push(`// --- Variant stories ---`, ``);
    for (const key of variantKeys) {
      const exportName = pascal(key);
      const desc = variants![key] ?? "";
      lines.push(`export const ${exportName}: Story = {`);
      lines.push(`  name: "${exportName} — ${desc.replace(/"/g, '\\"')}",`);
      lines.push(`  args: { variant: "${key}" },`);
      lines.push(`};`, ``);
    }
  }

  // Size stories
  if (sizeKeys.length > 0) {
    lines.push(`// --- Size stories ---`, ``);
    for (const key of sizeKeys) {
      const exportName = sizeLabel(key);
      lines.push(`export const ${exportName}: Story = {`);
      lines.push(`  args: { size: "${key}" },`);
      lines.push(`};`, ``);
    }
  }

  // State stories
  if (stateKeys.length > 0) {
    lines.push(`// --- State stories ---`, ``);
    for (const key of stateKeys) {
      const state = states![key];
      const exportName = pascal(key);
      lines.push(`export const ${exportName}: Story = {`);
      lines.push(`  args: {`);
      if (variantKeys[0]) lines.push(`    variant: "${variantKeys[0]}",`);
      if (state?.ariaDisabled) lines.push(`    disabled: true,`);
      if (key === "loading") lines.push(`    loading: true,`);
      if (state?.focusRing) lines.push(`    // Note: focus ring visible on keyboard focus`);
      lines.push(`  },`);
      if (state?.description) lines.push(`  // ${state.description}`);
      lines.push(`};`, ``);
    }
  }

  // AllVariants
  lines.push(`// --- Overview ---`, ``);
  lines.push(`export const AllVariants: Story = {`);
  lines.push(`  render: (_args) => (`);
  lines.push(`    // PLACEHOLDER: render all variants side by side`);
  if (fw === "react" && variantKeys.length > 0) {
    lines.push(`    // Example (React):`);
    lines.push(`    // <div style={{ display: "flex", gap: 8, flexWrap: "wrap" }}>`);
    for (const key of variantKeys) {
      lines.push(`    //   <${name} variant="${key}" />`);
    }
    lines.push(`    // </div>`);
  }
  lines.push(`    null`);
  lines.push(`  ),`);
  lines.push(`};`);

  return lines.join("\n") + "\n";
}
