/**
 * Foundation doc: grid.md
 *
 * Documents the responsive grid using window size classes (not device types).
 */

import type { NibBrandConfig } from "../../types/brand.js";

const DATE = new Date().toISOString().split("T")[0];

/** Generate grid.md */
export function generateGridDoc(_config: NibBrandConfig): string {
  return `# Grid System
<!-- nib-foundation: grid | generated: ${DATE} | do not edit manually -->

## Window Size Classes

The grid is defined in terms of **window size classes**, not device types. This distinction matters because:

- A tablet in Split View has a compact window, not a tablet window
- A foldable phone in unfolded state has an expanded window
- A desktop app in a small window is compact regardless of screen size
- iOS/iPadOS and Android both use this mental model natively

Always design to the window, not the device.

| Size class | Breakpoint token | Width range | Typical context |
|------------|-----------------|-------------|-----------------|
| **Compact** | \`breakpoint.xs\` → \`breakpoint.sm\` | < 480px | Small phones, Split View narrow pane |
| **Medium** | \`breakpoint.sm\` → \`breakpoint.md\` | 480px–768px | Large phones, small tablets, Split View wide pane |
| **Expanded** | \`breakpoint.md\` + | > 768px | Tablets, desktop windows, large-screen apps |

> Note: Some design systems use compact/medium/expanded at 600px and 840px (Material You). nib uses 480px and 768px to align with common web breakpoints. Adjust in \`.nib/brand.config.json\` if your product targets native platforms.

---

## Grid Specifications

### Compact (< 480px)

| Property | Value |
|----------|-------|
| Columns | 4 |
| Gutter | \`spacing.md\` (16px) |
| Margin | \`spacing.md\` (16px) |
| Max content width | 100% |

### Medium (480px – 768px)

| Property | Value |
|----------|-------|
| Columns | 8 |
| Gutter | \`spacing.lg\` (24px) |
| Margin | \`spacing.xl\` (32px) |
| Max content width | 100% |

### Expanded (> 768px)

| Property | Value |
|----------|-------|
| Columns | 12 |
| Gutter | \`spacing.lg\` (24px) |
| Margin | auto (centered) |
| Max content width | \`sizing.container.xl\` (1280px) |

---

## Layout Primitives by Size Class

| Pattern | Compact | Medium | Expanded |
|---------|---------|--------|----------|
| Navigation | Bottom tab bar / drawer | Side rail (collapsed) | Side nav (expanded) |
| List + detail | Stacked (push navigation) | Side-by-side (50/50) | Master-detail (30/70) |
| Form | Single column | Single column | Two-column optional |
| Cards | Single column | 2 columns | 3–4 columns |
| Modal | Full-screen sheet | Centered, max 560px | Centered, max 640px |

---

## Breakpoint Token Usage

### CSS

\`\`\`css
/* Compact: default */
.card-grid { grid-template-columns: 1fr; }

/* Medium: 2 columns */
@media (min-width: var(--breakpoint-sm)) {
  .card-grid { grid-template-columns: 1fr 1fr; }
}

/* Expanded: 3 columns */
@media (min-width: var(--breakpoint-md)) {
  .card-grid { grid-template-columns: 1fr 1fr 1fr; }
}
\`\`\`

### Tailwind

\`\`\`html
<div class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-6">
  <!-- cards -->
</div>
\`\`\`

The Tailwind preset generated by \`nib brand build\` maps breakpoint tokens to Tailwind's \`screens\` config automatically.

---

## Why Not Device Types?

Designing to device types (phone/tablet/desktop) breaks when:
- An iPad runs an app in a narrow Split View pane (behaves like a phone)
- A foldable phone is unfolded (behaves like a tablet)
- A user resizes a desktop browser window to 320px

Window size classes are **dynamic** and **accurate**. Device types are **static** and **wrong** for edge cases.

---

*Generated by nib. Run \`nib brand build\` to regenerate.*
`;
}
