/**
 * Component doc generator.
 *
 * generateComponentDoc(contract) → Markdown for docs/design/system/components/<Name>.md
 * generateComponentIndex(registry) → Markdown for docs/design/system/components.md
 */

import type { ComponentContract, ComponentRegistry } from "../../types/brand.js";

const DATE = new Date().toISOString().split("T")[0];

/** APG pattern URLs per widget type */
const APG_URLS: Record<string, string> = {
  button: "https://www.w3.org/WAI/ARIA/apg/patterns/button/",
  textinput: "https://www.w3.org/WAI/ARIA/apg/patterns/textbox/",
  checkbox: "https://www.w3.org/WAI/ARIA/apg/patterns/checkbox/",
  radio: "https://www.w3.org/WAI/ARIA/apg/patterns/radio/",
  switch: "https://www.w3.org/WAI/ARIA/apg/patterns/switch/",
  tabs: "https://www.w3.org/WAI/ARIA/apg/patterns/tabs/",
  dialog: "https://www.w3.org/WAI/ARIA/apg/patterns/dialog-modal/",
  combobox: "https://www.w3.org/WAI/ARIA/apg/patterns/combobox/",
  tooltip: "https://www.w3.org/WAI/ARIA/apg/patterns/tooltip/",
};

/** Format keyboard map as a Markdown table */
function keyboardTable(keyboard: Record<string, string>): string {
  if (Object.keys(keyboard).length === 0) return "_No keyboard bindings defined._";

  const rows = Object.entries(keyboard)
    .map(([key, desc]) => `| \`${key}\` | ${desc} |`)
    .join("\n");
  return `| Key | Behavior |\n|-----|----------|\n${rows}`;
}

/** Format anatomy as a Markdown table */
function anatomyTable(anatomy: Record<string, string>): string {
  const rows = Object.entries(anatomy)
    .map(([part, desc]) => `| \`${part}\` | ${desc} |`)
    .join("\n");
  return `| Part | Description |\n|------|-------------|\n${rows}`;
}

/** Format states as a Markdown table */
function statesTable(states: ComponentContract["states"]): string {
  const rows = Object.entries(states)
    .map(([state, def]) => `| \`${state}\` | ${def.description}${def.focusRing ? " (focus ring)" : ""}${def.ariaDisabled ? " (aria-disabled)" : ""} |`)
    .join("\n");
  return `| State | Description |\n|-------|-------------|\n${rows}`;
}

/** Format token bindings as a code block */
function tokenBlock(tokens: ComponentContract["tokens"]): string {
  return "```json\n" + JSON.stringify(tokens, null, 2) + "\n```";
}

/**
 * Generate a Markdown doc for a single component contract.
 * Writes to docs/design/system/components/<Name>.md.
 */
export function generateComponentDoc(contract: ComponentContract): string {
  const apgUrl = APG_URLS[contract.widgetType];
  const apgLink = apgUrl
    ? `**WAI-ARIA APG:** [${contract.widgetType} pattern](${apgUrl})`
    : "";

  const variantSection = contract.variants
    ? `## Variants\n\n${Object.entries(contract.variants)
        .map(([name, desc]) => `- \`${name}\` — ${desc}`)
        .join("\n")}\n`
    : "";

  const sizeSection =
    contract.sizes && Object.keys(contract.sizes).length > 0
      ? `## Sizes\n\n${Object.entries(contract.sizes)
          .map(([name, props]) => {
            const propStr = Object.entries(props)
              .map(([k, v]) => `${k}: ${v ?? ""}`)
              .join(", ");
            return `- \`${name}\` — ${propStr}`;
          })
          .join("\n")}\n`
      : "";

  const touchTarget = contract.a11y.minimumTouchTarget;

  return `# ${contract.name}
<!-- nib-component: v1 | generated: ${DATE} | do not edit manually -->

> ${contract.description}

**Widget type:** \`${contract.widgetType}\`${apgUrl ? `
${apgLink}` : ""}

---

## Anatomy

${anatomyTable(contract.anatomy)}

---

## States

${statesTable(contract.states)}

---

${variantSection}${sizeSection}## Accessibility

**ARIA role:** \`${contract.a11y.role}\`
**Focus behavior:** ${contract.a11y.focusBehavior}
**Focus trap:** ${contract.a11y.focusTrap ? "Yes" : "No"}
${contract.a11y.focusReturnTarget ? `**Focus returns to:** ${contract.a11y.focusReturnTarget}  \n` : ""}**Required label:** ${contract.a11y.requiredLabel ? "Yes" : "No"} (${contract.a11y.labelStrategy})
**Touch target minimum:** ${touchTarget.ios} iOS / ${touchTarget.android} Android / ${touchTarget.web} web

### Keyboard Interaction

${keyboardTable(contract.a11y.keyboard)}

### ARIA Attributes

${contract.a11y.ariaAttributes.map((a) => `- \`${a}\``).join("\n")}

---

## Token Bindings

${tokenBlock(contract.tokens)}

---

*Generated by nib. Run \`nib brand build\` to regenerate.*
`;
}

/**
 * Generate a Markdown index of all components in the registry.
 * Writes to docs/design/system/components.md.
 */
export function generateComponentIndex(
  registry: ComponentRegistry,
  contracts: Map<string, ComponentContract>,
): string {
  const entries = Object.entries(registry);

  if (entries.length === 0) {
    return `# Component System
<!-- nib-components-index: v1 | generated: ${DATE} | do not edit manually -->

_No components defined yet. Run \`nib component init <Name>\` to scaffold your first component._
`;
  }

  const tableRows = entries
    .map(([name, entry]) => {
      const contract = contracts.get(name);
      const stateCount = contract ? Object.keys(contract.states).length : 0;
      const variantCount = contract?.variants ? Object.keys(contract.variants).length : 0;
      return `| [${name}](components/${name}.md) | ${entry.widgetType} | ${entry.status} | ${stateCount} | ${variantCount} |`;
    })
    .join("\n");

  const componentSections = entries
    .map(([name, entry]) => {
      const contract = contracts.get(name);
      if (!contract) return `### ${name}\n\n> _Contract not loaded._\n`;

      const stateList = Object.keys(contract.states).join(", ");
      const keyboardEntries = Object.entries(contract.a11y.keyboard);
      const keyboardStr =
        keyboardEntries.length > 0
          ? keyboardEntries.map(([k, v]) => `\`${k}\` → ${v}`).join(", ")
          : "_none_";
      const touchTarget = contract.a11y.minimumTouchTarget;

      return `### ${name}
> ${contract.description}

**Anatomy:** ${Object.keys(contract.anatomy).join(", ")}
**States:** ${stateList}
**Keyboard:** ${keyboardStr}
**Touch target:** ${touchTarget.ios} iOS / ${touchTarget.android} Android / ${touchTarget.web} web
`;
    })
    .join("\n---\n\n");

  return `# Component System
<!-- nib-components-index: v1 | generated: ${DATE} | do not edit manually -->

## Registry

| Component | Widget Type | Status | States | Variants |
|-----------|-------------|--------|--------|----------|
${tableRows}

---

## Components

${componentSections}

---

*Generated by nib. Run \`nib brand build\` to regenerate.*
`;
}
