/**
 * Integration tests for brand/build.ts — DTCG tokens → CSS/Tailwind outputs.
 *
 * Creates a minimal fixture token directory in a temp dir, calls buildCss
 * and buildTailwindPreset, and asserts the output content.
 */

import { describe, it, expect, beforeAll, afterAll } from "bun:test";
import { mkdtemp, mkdir, writeFile, readFile, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { buildCss, buildTailwindPreset } from "./build.js";

// ─── Fixture helpers ──────────────────────────────────────────────────────────

/** Minimal set of token files sufficient for buildCss and buildTailwindPreset. */
const FIXTURES: Record<string, unknown> = {
  "color/primitives.tokens.json": {
    color: {
      $type: "color",
      white: { $value: "#ffffff" },
      black: { $value: "#000000" },
      brand: {
        "400": { $value: "#60a5fa" },
        "500": { $value: "#3b82f6" },
        "600": { $value: "#2563eb" },
        "700": { $value: "#1d4ed8" },
      },
      neutral: {
        "50":  { $value: "#f9fafb" },
        "200": { $value: "#e5e7eb" },
        "600": { $value: "#4b5563" },
        "700": { $value: "#374151" },
        "900": { $value: "#111827" },
        "950": { $value: "#030712" },
      },
    },
  },
  "color/semantic-light.tokens.json": {
    color: {
      $type: "color",
      background: { primary: { $value: "{color.white}" } },
      text: { primary: { $value: "{color.neutral.900}" } },
      interactive: { default: { $value: "{color.brand.600}" } },
    },
  },
  "color/semantic-dark.tokens.json": {
    color: {
      $type: "color",
      background: { primary: { $value: "{color.neutral.950}" } },
      text: { primary: { $value: "{color.neutral.50}" } },
      interactive: { default: { $value: "{color.brand.400}" } },
    },
  },
  "typography.tokens.json": {
    "font-family": {
      sans: { $value: "Inter, sans-serif", $type: "fontFamily" },
      mono: { $value: "JetBrains Mono, monospace", $type: "fontFamily" },
    },
    "font-size": {
      base: { $value: "16px", $type: "dimension" },
      lg: { $value: "18px", $type: "dimension" },
    },
  },
  "spacing.tokens.json": {
    spacing: {
      sm: { $value: "8px", $type: "dimension" },
      md: { $value: "16px", $type: "dimension" },
      lg: { $value: "24px", $type: "dimension" },
    },
  },
  "border-radius.tokens.json": {
    "border-radius": {
      sm: { $value: "4px", $type: "dimension" },
      md: { $value: "6px", $type: "dimension" },
      lg: { $value: "8px", $type: "dimension" },
    },
  },
  "elevation.tokens.json": {
    elevation: {
      sm: {
        $value: { offsetX: "0px", offsetY: "1px", blur: "2px", spread: "0px", color: "rgba(0,0,0,0.05)" },
        $type: "shadow",
      },
    },
  },
  "motion.tokens.json": {
    duration: {
      fast: { $value: "100ms", $type: "duration" },
      normal: { $value: "200ms", $type: "duration" },
    },
  },
  "sizing.tokens.json": {
    sizing: {
      icon: { $value: "24px", $type: "dimension" },
    },
  },
  "border-width.tokens.json": {
    "border-width": {
      default: { $value: "1px", $type: "dimension" },
    },
  },
  "opacity.tokens.json": {
    opacity: {
      disabled: { $value: "0.4", $type: "number" },
    },
  },
  "z-index.tokens.json": {
    "z-index": {
      modal: { $value: "1000", $type: "number" },
    },
  },
  "breakpoints.tokens.json": {
    breakpoint: {
      md: { $value: "768px", $type: "dimension" },
      lg: { $value: "1024px", $type: "dimension" },
    },
  },
};

// ─── Setup / teardown ─────────────────────────────────────────────────────────

let tmpDir: string;

beforeAll(async () => {
  tmpDir = await mkdtemp(join(tmpdir(), "nib-build-test-"));

  // Write all fixture files, creating any needed subdirectories
  for (const [relPath, content] of Object.entries(FIXTURES)) {
    const fullPath = join(tmpDir, "tokens", relPath);
    const dirPath = fullPath.includes("/")
      ? fullPath.slice(0, fullPath.lastIndexOf("/"))
      : join(tmpDir, "tokens");
    await mkdir(dirPath, { recursive: true });
    await writeFile(fullPath, JSON.stringify(content, null, 2));
  }
});

afterAll(async () => {
  await rm(tmpDir, { recursive: true, force: true });
});

// ─── buildCss ─────────────────────────────────────────────────────────────────

describe("buildCss", () => {
  let css: string;

  beforeAll(async () => {
    const tokensDir = join(tmpDir, "tokens");
    const outputPath = join(tmpDir, "output", "variables.css");
    await buildCss(tokensDir, outputPath);
    css = await readFile(outputPath, "utf-8");
  });

  it("writes a non-empty CSS file", () => {
    expect(css.length).toBeGreaterThan(0);
  });

  it("starts with a generated-by comment", () => {
    expect(css).toContain("Generated by nib brand build");
  });

  it("has a :root block", () => {
    expect(css).toContain(":root {");
  });

  it("emits primitive color variables with -- prefix", () => {
    expect(css).toContain("--color-white: #ffffff");
    expect(css).toContain("--color-black: #000000");
    expect(css).toContain("--color-brand-600: #2563eb");
    expect(css).toContain("--color-neutral-900: #111827");
  });

  it("emits semantic light variables with CSS var() references", () => {
    expect(css).toContain("--color-background-primary: var(--color-white)");
    expect(css).toContain("--color-text-primary: var(--color-neutral-900)");
    expect(css).toContain("--color-interactive-default: var(--color-brand-600)");
  });

  it("emits spacing variables", () => {
    expect(css).toContain("--spacing-md: 16px");
    expect(css).toContain("--spacing-lg: 24px");
  });

  it("emits border-radius variables", () => {
    expect(css).toContain("--border-radius-md: 6px");
  });

  it("emits typography variables", () => {
    expect(css).toContain("--font-size-base: 16px");
  });

  it("has a dark mode @media block", () => {
    expect(css).toContain("@media (prefers-color-scheme: dark)");
  });

  it("has a [data-theme=dark] block", () => {
    expect(css).toContain('[data-theme="dark"]');
  });

  it("dark theme overrides use dark semantic values", () => {
    // Dark background should point to neutral.950
    expect(css).toContain("var(--color-neutral-950)");
    // Dark interactive should point to brand.400
    expect(css).toContain("var(--color-brand-400)");
  });

  it("resolves DTCG references {foo.bar} → var(--foo-bar) in semantic tokens", () => {
    // Semantic light: interactive.default = {color.brand.600} → var(--color-brand-600)
    expect(css).toContain("var(--color-brand-600)");
  });
});

// ─── buildTailwindPreset ──────────────────────────────────────────────────────

describe("buildTailwindPreset", () => {
  let preset: string;

  beforeAll(async () => {
    const tokensDir = join(tmpDir, "tokens");
    const outputPath = join(tmpDir, "output", "preset.js");
    await buildTailwindPreset(tokensDir, outputPath);
    preset = await readFile(outputPath, "utf-8");
  });

  it("writes a non-empty JS file", () => {
    expect(preset.length).toBeGreaterThan(0);
  });

  it("exports a default object", () => {
    expect(preset).toContain("export default");
  });

  it("contains a theme.extend section", () => {
    expect(preset).toContain("theme");
    expect(preset).toContain("extend");
  });

  it("includes primitive brand color keys", () => {
    // Tailwind preset uses CSS var() references, not raw hex values
    expect(preset).toContain("brand");
    expect(preset).toContain("var(--color-brand-600)");
  });

  it("includes semantic color entries", () => {
    expect(preset).toContain("interactive");
    expect(preset).toContain("var(--color-interactive-default)");
  });

  it("includes spacing keys referencing CSS variables", () => {
    expect(preset).toContain("spacing");
    expect(preset).toContain("var(--spacing-md)");
  });

  it("includes border radius values", () => {
    expect(preset).toContain("borderRadius");
    expect(preset).toContain("var(--border-radius-md)");
  });

  it("is valid JavaScript (no syntax errors from JSON serialization)", () => {
    // Should not have raw {color.brand.600} references in resolved values
    expect(preset).not.toMatch(/\{color\.\w/);
  });
});
